name: Invoke Lambda on Push to Main

on:
  push:
    branches:
      - main

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  

      - name: Invoke Lambda Function
        run: |
          aws lambda invoke --function-name MyLambdaFunction --payload file://data.json response.json --cli-binary-format raw-in-base64-out